### PR TITLE
Fix broken MLB scores scraping

### PR DESCRIPTION
**Pull request by dgmdan**
It looks like ESPN changed their layout, breaking MLB scores in this gem. This allows MLB scores to be scraped from the current layout.

I also updated the tests to use minitest. Not sure if this is alright but it seemed like the path of least resistance to getting tests running. Some tests still fail (test_college_football_2012_week_9_regular_season, test_scrape_ncaa_basketball_teams, test_scrape_nhl_teams) but I'm only attempting to fix the MLB scores here.

### CODE REVIEW

**Comment by aj0strow** [comment]
Thanks for this. I'll look into it on the weekend.

**Comment by aj0strow** [comment]
I cloned your branch, and the test suite didn't pass for me. Which version of ruby are you using? 

Will look into it more this coming week, been a bit since i used this gem.

**Comment by dgmdan** [comment]
I was using ruby 2.1. I made some more changes so that it will run in 1.9 and newer. I figured 1.8 wasn't necessary since you use nokogiri which doesn't work on 1.8.

I have to make another change though. This code has a bug where it does not see games that go into extra innings. This is because it's looking for a status of "Final" when the status could be "Final/10" in the case of extra innings. I'll fix that shortly and add some more tests.

**Comment by aj0strow** [comment]
@dgmdan sounds good, look forward

**Comment by dgmdan** [comment]
Okay, all set, I've fixed the bug and added a test that looks for a known extra innings game.

**Comment by aj0strow** [comment]
Thanks this is great stuff. 

```
-- before --
2 tests, 1 assertions, 1 failures, 0 errors, 0 skips

-- after --
3 tests, 2 assertions, 0 failures, 0 errors, 0 skips
```

**Pull request merged**
